# Generated by Django 5.0.1 on 2024-07-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCPLapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='preserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=500)),
                ('lr_date', models.CharField(max_length=500)),
                ('dist_name', models.CharField(max_length=500)),
                ('dist_town', models.CharField(max_length=500)),
                ('trnas_name', models.CharField(max_length=500)),
                ('v_type', models.CharField(max_length=500)),
                ('v_no', models.CharField(max_length=500)),
                ('l_type', models.CharField(max_length=500)),
                ('invoice_no', models.CharField(max_length=500)),
                ('invoice_val', models.CharField(max_length=500)),
                ('quantity', models.CharField(max_length=500)),
                ('invoice_date', models.CharField(max_length=500)),
                ('weight', models.CharField(max_length=500)),
                ('labour_exp', models.CharField(max_length=500)),
                ('freight', models.CharField(max_length=500)),
                ('misc_charge', models.CharField(max_length=500)),
                ('total_amt', models.CharField(max_length=500)),
                ('advance_amnt', models.CharField(max_length=500)),
                ('due_amnt', models.CharField(max_length=500)),
                ('product', models.CharField(max_length=500)),
                ('diponame', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
