# Generated by Django 5.0.1 on 2024-07-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCPLapp', '0003_alter_preserve_advance_amnt_alter_preserve_dist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='quan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order_details',
            name='weig',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preserve',
            name='quan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preserve',
            name='weig',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
