# Generated by Django 5.0.1 on 2024-07-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCPLapp', '0004_order_details_quan_order_details_weig_preserve_quan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preserve',
            name='quan',
        ),
        migrations.RemoveField(
            model_name='preserve',
            name='weig',
        ),
    ]
