# Generated by Django 5.0.1 on 2024-07-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCPLapp', '0005_remove_preserve_quan_remove_preserve_weig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='quan',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='weig',
        ),
    ]
