# Generated by Django 5.0.1 on 2024-07-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCPLapp', '0006_remove_order_details_quan_remove_order_details_weig'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='quan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order_details',
            name='weig',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
