# Generated by Django 5.0.1 on 2024-07-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCPLapp', '0007_order_details_quan_order_details_weig'),
    ]

    operations = [
        migrations.AddField(
            model_name='preserve',
            name='quan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preserve',
            name='weig',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
