# Generated by Django 5.0.1 on 2024-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCPLapp', '0008_preserve_quan_preserve_weig'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='advance_per',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preserve',
            name='advance_per',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
