# Generated by Django 5.1.6 on 2025-02-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCPLapp', '0009_order_details_advance_per_preserve_advance_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='distri_details',
            name='qrCode',
            field=models.FileField(null=True, upload_to='QRCodes/'),
        ),
    ]
