# Generated by Django 5.1.6 on 2025-02-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCPLapp', '0010_distri_details_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='markAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
